export const StakingAccountStatuses = {
  STARTED: "STARTED",
  STAKED: "STAKED",
  STAKE_REQUESTED: "STAKE_REQUESTED",
  UNSTAKE_REQUESTED: "UNSTAKE_REQUESTED",
  COMPLETED: "COMPLETED",
  INVALIDATED: "INVALIDATED",
  CANCELED: "CANCELED"
};

export const StakingAccountTokenTypes = {
  WAIFU: "WAIFU",
  WEAPON: "WEAPON"
};